In [3]:
import numpy as np
def moving_average(a,n=3):
    ret = np.cumsum(a, dtype=float)
    

[0 1 2 3 4 5]


In [5]:
csum = np.cumsum(a, dtype=float)
print(csum)

[  0.   1.   3.   6.  10.  15.]


In [7]:
b = csum[3:]
print(b)

[  6.  10.  15.]


In [9]:
c = csum[:-3]
print(c)

[ 0.  1.  3.]


In [10]:
d = b - c
print(d)

[  6.   9.  12.]
